services:
  api:
    build: .
    container_name: lesdefisjs-api
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./sandbox-tmp:/sandbox-tmp
    environment:
      SANDBOX_CONTAINER_DIR: /sandbox-tmp
      SANDBOX_HOST_DIR: ${SANDBOX_HOST_DIR}